services:
  postgres:
    image: postgres:16
    container_name: game_postgres
    environment:
      POSTGRES_USER: game
      POSTGRES_PASSWORD: gameps
      POSTGRES_DB: gamedb
    ports:
      - "5500:5500"
    volumes:
      - pgdata:/var/lib/postgresql/data
        
  redis:
    image: redis:7
    container_name: :game_redis
    ports:
      - "6379:6379"
  
  volumes:
    pgdata: